name: nv-llm
channels:
  - conda-forge
  - defaults
dependencies:
  - aiofiles=22.1.0=py312haa95532_0
  - aiohttp=3.9.5=py312h2bbff1b_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - altair=5.0.1=py312haa95532_0
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312haa95532_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - babel=2.11.0=py312haa95532_0
  - beautifulsoup4=4.12.2=py312haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.7=py312he558020_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py312hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.6.2=h56e8100_0
  - certifi=2024.6.2=py312haa95532_0
  - cffi=1.16.0=py312h2bbff1b_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=py312haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.1=py312haa95532_0
  - contourpy=1.2.0=py312h59b6b97_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses-json=0.6.6=pyhd8ed1ab_0
  - debugpy=1.6.7=py312hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py312haa95532_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=hd77b12b_0
  - ffmpeg=4.2.2=he774522_0
  - ffmpy=0.3.0=pyhb6f538c_0
  - filelock=3.13.1=py312haa95532_0
  - fonttools=4.51.0=py312h2bbff1b_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.4.0=py312h2bbff1b_0
  - fsspec=2024.3.1=py312haa95532_0
  - gradio=4.36.1=pyhd8ed1ab_0
  - gradio-client=1.0.1=pyhd8ed1ab_0
  - greenlet=3.0.1=py312hd77b12b_0
  - h11=0.14.0=py312haa95532_0
  - huggingface_hub=0.23.1=py312haa95532_0
  - icu=73.1=h6c2663c_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-resources=6.1.1=pyhd3eb1b0_1
  - importlib_resources=6.1.1=py312haa95532_1
  - intel-openmp=2023.2.0=h57928b3_50497
  - ipykernel=6.28.0=py312haa95532_0
  - ipython=8.20.0=py312haa95532_0
  - ipywidgets=8.1.2=py312haa95532_0
  - jedi=0.18.1=py312haa95532_1
  - jinja2=3.1.4=py312haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.19.2=py312haa95532_0
  - jsonschema-specifications=2023.7.1=py312haa95532_0
  - jupyter=1.0.0=py312haa95532_9
  - jupyter-lsp=2.2.0=py312haa95532_0
  - jupyter_client=8.6.0=py312haa95532_0
  - jupyter_console=6.6.3=py312haa95532_1
  - jupyter_core=5.5.0=py312haa95532_0
  - jupyter_events=0.8.0=py312haa95532_0
  - jupyter_server=2.10.0=py312haa95532_0
  - jupyter_server_terminals=0.4.4=py312haa95532_1
  - jupyterlab=4.0.11=py312haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py312haa95532_0
  - jupyterlab_widgets=3.0.10=py312haa95532_0
  - kiwisolver=1.4.4=py312hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - langchain=0.1.20=pyhd8ed1ab_0
  - langchain-community=0.0.38=pyhd8ed1ab_0
  - langchain-core=0.1.52=pyhd8ed1ab_0
  - langchain-text-splitters=0.0.2=pyhd8ed1ab_0
  - langsmith=0.1.69=pyhd8ed1ab_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.9.1=h51c2c0f_0
  - libiconv=1.17=hcfcfb64_2
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.10.4=h0ad7f3c_2
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py312h2bbff1b_0
  - marshmallow=3.21.2=pyhd8ed1ab_0
  - matplotlib-base=3.8.4=py312hc7c4135_0
  - matplotlib-inline=0.1.6=py312haa95532_0
  - mistune=2.0.4=py312haa95532_0
  - mkl=2023.2.0=h6a75c08_50497
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.8=py312h2bbff1b_0
  - mkl_random=1.2.4=py312h59b6b97_0
  - multidict=6.0.4=py312h2bbff1b_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclient=0.8.0=py312haa95532_0
  - nbconvert=7.10.0=py312haa95532_0
  - nbformat=5.9.2=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - notebook=7.0.8=py312haa95532_0
  - notebook-shim=0.2.3=py312haa95532_0
  - numexpr=2.8.7=py312h96b7d27_0
  - numpy=1.26.4=py312hfd52020_0
  - numpy-base=1.26.4=py312h4dde369_0
  - openai=1.25.0=py312haa95532_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.3.0=h2466b09_3
  - orjson=3.9.15=py312h2bbff1b_0
  - overrides=7.4.0=py312haa95532_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.2.1=py312h0158946_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pillow=10.3.0=py312h2bbff1b_0
  - pip=24.0=py312haa95532_0
  - platformdirs=3.10.0=py312haa95532_0
  - ply=3.11=py312haa95532_1
  - prometheus_client=0.14.1=py312haa95532_0
  - prompt-toolkit=3.0.43=py312haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h2bbff1b_0
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.5.3=pyhd8ed1ab_0
  - pydantic-core=2.14.6=py312h062c2fa_0
  - pydub=0.25.1=pyhd8ed1ab_0
  - pygments=2.15.1=py312haa95532_1
  - pyparsing=3.0.9=py312haa95532_0
  - pyqt=5.15.10=py312hd77b12b_0
  - pyqt5-sip=12.13.0=py312h2bbff1b_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.12.3=h1d929f7_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.16.2=py312haa95532_0
  - python-json-logger=2.0.7=py312haa95532_0
  - python-multipart=0.0.9=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312haa95532_0
  - pywin32=305=py312h2bbff1b_0
  - pywinpty=2.0.10=py312h5da7b33_0
  - pyyaml=6.0.1=py312h2bbff1b_0
  - pyzmq=25.1.2=py312hd77b12b_0
  - qt-main=5.15.2=h19c9488_10
  - qtconsole=5.5.1=py312haa95532_0
  - qtpy=2.4.1=py312haa95532_0
  - referencing=0.30.2=py312haa95532_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=py312haa95532_0
  - rfc3986-validator=0.1.1=py312haa95532_0
  - rpds-py=0.10.6=py312h062c2fa_0
  - ruff=0.3.5=py312h36a85e1_0
  - semantic_version=2.8.5=pyhd3eb1b0_0
  - send2trash=1.8.2=py312haa95532_0
  - setuptools=69.5.1=py312haa95532_0
  - sip=6.7.12=py312hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=py312haa95532_0
  - sqlalchemy=2.0.25=py312h2bbff1b_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.9.0=h91493d7_0
  - tenacity=8.3.0=pyhd8ed1ab_0
  - terminado=0.17.1=py312haa95532_0
  - tinycss2=1.2.1=py312haa95532_0
  - tk=8.6.14=h0416ee5_0
  - tomlkit=0.12.0=pyha770c72_0
  - toolz=0.12.0=py312haa95532_0
  - tornado=6.3.3=py312h2bbff1b_0
  - tqdm=4.66.4=py312hfc267ef_0
  - traitlets=5.7.1=py312haa95532_0
  - typing-extensions=4.12.1=hd8ed1ab_0
  - typing_extensions=4.12.1=pyha770c72_0
  - typing_inspect=0.9.0=pyhd8ed1ab_0
  - tzdata=2024a=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.1.0=py312h2bbff1b_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.2=h2eaa2aa_1
  - vc14_runtime=14.38.33135=h835141b_20
  - vs2015_runtime=14.38.33135=h22015db_20
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312haa95532_2
  - websocket-client=1.8.0=py312haa95532_0
  - wheel=0.43.0=py312haa95532_0
  - widgetsnbextension=4.0.10=py312haa95532_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.9.3=py312h2bbff1b_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.5=hd43e919_2
  - pip:
      - asgiref==3.8.1
      - backoff==2.2.1
      - bcrypt==4.1.3
      - build==1.2.1
      - cachetools==5.3.3
      - castxml==0.4.5
      - chroma-hnswlib==0.7.3
      - chromadb==0.5.0
      - coloredlogs==15.0.1
      - deprecated==1.2.14
      - dnspython==2.6.1
      - email-validator==2.1.1
      - faiss-cpu==1.8.0
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - flatbuffers==24.3.25
      - google-auth==2.30.0
      - googleapis-common-protos==1.63.1
      - gpt4all==2.7.0
      - grpcio==1.64.1
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - humanfriendly==10.0
      - importlib-metadata==7.1.0
      - kubernetes==30.1.0
      - langchain-chroma==0.1.1
      - langchain-nvidia-ai-endpoints==0.1.2
      - langserve==0.2.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mmh3==4.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - oauthlib==3.2.2
      - onnxruntime==1.18.0
      - opentelemetry-api==1.25.0
      - opentelemetry-exporter-otlp-proto-common==1.25.0
      - opentelemetry-exporter-otlp-proto-grpc==1.25.0
      - opentelemetry-instrumentation==0.46b0
      - opentelemetry-instrumentation-asgi==0.46b0
      - opentelemetry-instrumentation-fastapi==0.46b0
      - opentelemetry-proto==1.25.0
      - opentelemetry-sdk==1.25.0
      - opentelemetry-semantic-conventions==0.46b0
      - opentelemetry-util-http==0.46b0
      - posthog==3.5.0
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygccxml==2.5.0
      - pypika==0.48.9
      - pyproject-hooks==1.1.0
      - pyproject-toml==0.0.10
      - pyreadline3==3.4.1
      - python-dotenv==1.0.1
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rsa==4.9
      - shellingham==1.5.4
      - sse-starlette==1.8.2
      - starlette==0.37.2
      - sympy==1.12.1
      - tokenizers==0.19.1
      - toml==0.10.2
      - typer==0.12.3
      - ujson==5.10.0
      - uvicorn==0.30.1
      - watchfiles==0.22.0
      - websockets==12.0
      - wrapt==1.16.0
      - zipp==3.19.2
prefix: C:\Installs\Miniconda3\envs\nv-llm
